name: "Build"
on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build project
        run: ./gradlew check assembleDebug packageDistributionForCurrentOS
