name: "Publish"
on:
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode Keystore
        run: 'echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > keystore/keystore.jks'

      - name: Build release project
        run: ./gradlew assembleRelease
        env:
          ANDROID_KEYSTORE_PASSWORD : ${{ secrets.ANDROID_KEYSTORE_PASSWORD  }}
          ANDROID_KEY_ALIAS : ${{ secrets.ANDROID_KEY_ALIAS  }}
          ANDROID_KEY_PASSWORD : ${{ secrets.ANDROID_KEY_PASSWORD  }}

      - name: Attach release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            composeApp/build/outputs/apk/release/composeApp-release.apk
