name: Sync Repository Secrets and Variables

on:
  workflow_dispatch:

jobs:
  sync-repo-secrets-and-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Secrets and Variables
        uses: cbrgm/sync-secrets-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: 'ILikeYourHat/Whippet'
          secrets: |
            ANDROID_KEYSTORE=${{ secrets.ANDROID_KEYSTORE }}
            ANDROID_KEYSTORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
            ANDROID_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}
            ANDROID_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}
